SELECT
`feedstuffs`.`id` AS `id`,
`feedstuffs`.`name` AS `name`,
`feedstuffs`.`sortOrder` AS `sortOrder`,
fnGetElementValue(`feedstuffs`.`id`, 'DM') AS 'DM',
fnGetElementValue(`feedstuffs`.`id`, 'CP') AS 'CP',
fnGetElementValue(`feedstuffs`.`id`, 'RUP') AS 'RUP',
fnGetElementValue(`feedstuffs`.`id`, 'CF') AS 'CF',
fnGetElementValue(`feedstuffs`.`id`, 'EE') AS 'EE',
fnGetElementValue(`feedstuffs`.`id`, 'EEP') AS 'EEP',
fnGetElementValue(`feedstuffs`.`id`, 'Linoleic') AS 'Linoleic',
fnGetElementValue(`feedstuffs`.`id`, 'Arachid') AS 'Arachid',
fnGetElementValue(`feedstuffs`.`id`, 'ADF') AS 'ADF',
fnGetElementValue(`feedstuffs`.`id`, 'NDF') AS 'NDF',
fnGetElementValue(`feedstuffs`.`id`, 'eNDF') AS 'eNDF',
fnGetElementValue(`feedstuffs`.`id`, 'TDNCamelids') AS 'TDNCamelids',
fnGetElementValue(`feedstuffs`.`id`, 'TDNCattle') AS 'TDNCattle',
fnGetElementValue(`feedstuffs`.`id`, 'TDNSheep') AS 'TDNSheep',
fnGetElementValue(`feedstuffs`.`id`, 'DEAntelope') AS 'DEAntelope',
fnGetElementValue(`feedstuffs`.`id`, 'DECamelids') AS 'DECamelids',
fnGetElementValue(`feedstuffs`.`id`, 'DEDeer') AS 'DEDeer',
fnGetElementValue(`feedstuffs`.`id`, 'DEHorse') AS 'DEHorse',
fnGetElementValue(`feedstuffs`.`id`, 'DEPig') AS 'DEPig',
fnGetElementValue(`feedstuffs`.`id`, 'DESheep') AS 'DESheep',
fnGetElementValue(`feedstuffs`.`id`, 'MECattle') AS 'MECattle',
fnGetElementValue(`feedstuffs`.`id`, 'MECats') AS 'MECats',
fnGetElementValue(`feedstuffs`.`id`, 'MEDogs') AS 'MEDogs',
fnGetElementValue(`feedstuffs`.`id`, 'MEFish') AS 'MEFish',
fnGetElementValue(`feedstuffs`.`id`, 'MEPig') AS 'MEPig',
fnGetElementValue(`feedstuffs`.`id`, 'MEPoultry') AS 'MEPoultry',
fnGetElementValue(`feedstuffs`.`id`, 'MESheep') AS 'MESheep',
fnGetElementValue(`feedstuffs`.`id`, 'NEmCattle') AS 'NEmCattle',
fnGetElementValue(`feedstuffs`.`id`, 'NEgCattle') AS 'NEgCattle',
fnGetElementValue(`feedstuffs`.`id`, 'NElCattle') AS 'NElCattle',
fnGetElementValue(`feedstuffs`.`id`, 'Arg') AS 'Arg',
fnGetElementValue(`feedstuffs`.`id`, 'His') AS 'His',
fnGetElementValue(`feedstuffs`.`id`, 'Iso-L') AS 'Iso-L',
fnGetElementValue(`feedstuffs`.`id`, 'Leu') AS 'Leu',
fnGetElementValue(`feedstuffs`.`id`, 'Lys') AS 'Lys',
fnGetElementValue(`feedstuffs`.`id`, 'Avail Lys') AS 'Avail Lys',
fnGetElementValue(`feedstuffs`.`id`, 'Met') AS 'Met',
fnGetElementValue(`feedstuffs`.`id`, 'Cys') AS 'Cys',
fnGetElementValue(`feedstuffs`.`id`, 'Phe') AS 'Phe',
fnGetElementValue(`feedstuffs`.`id`, 'Proline') AS 'Proline',
fnGetElementValue(`feedstuffs`.`id`, 'Taurine') AS 'Taurine',
fnGetElementValue(`feedstuffs`.`id`, 'Tyr') AS 'Tyr',
fnGetElementValue(`feedstuffs`.`id`, 'Thr') AS 'Thr',
fnGetElementValue(`feedstuffs`.`id`, 'Trp') AS 'Trp',
fnGetElementValue(`feedstuffs`.`id`, 'Val') AS 'Val',
fnGetElementValue(`feedstuffs`.`id`, 'Gly') AS 'Gly',
fnGetElementValue(`feedstuffs`.`id`, 'Ser') AS 'Ser',
fnGetElementValue(`feedstuffs`.`id`, 'Ca') AS 'Ca',
fnGetElementValue(`feedstuffs`.`id`, 'Cl') AS 'Cl',
fnGetElementValue(`feedstuffs`.`id`, 'Mg') AS 'Mg',
fnGetElementValue(`feedstuffs`.`id`, 'P') AS 'P',
fnGetElementValue(`feedstuffs`.`id`, 'Avail P') AS 'Avail P',
fnGetElementValue(`feedstuffs`.`id`, 'K') AS 'K',
fnGetElementValue(`feedstuffs`.`id`, 'Na') AS 'Na',
fnGetElementValue(`feedstuffs`.`id`, 'S') AS 'S',
fnGetElementValue(`feedstuffs`.`id`, 'Co') AS 'Co',
fnGetElementValue(`feedstuffs`.`id`, 'Cr') AS 'Cr',
fnGetElementValue(`feedstuffs`.`id`, 'Cu') AS 'Cu',
fnGetElementValue(`feedstuffs`.`id`, 'I') AS 'I',
fnGetElementValue(`feedstuffs`.`id`, 'Fe') AS 'Fe',
fnGetElementValue(`feedstuffs`.`id`, 'Mn') AS 'Mn',
fnGetElementValue(`feedstuffs`.`id`, 'Se') AS 'Se',
fnGetElementValue(`feedstuffs`.`id`, 'Zn') AS 'Zn',
fnGetElementValue(`feedstuffs`.`id`, 'Mo') AS 'Mo',
fnGetElementValue(`feedstuffs`.`id`, 'Vit A') AS 'Vit A',
fnGetElementValue(`feedstuffs`.`id`, 'Vit D') AS 'Vit D',
fnGetElementValue(`feedstuffs`.`id`, 'Vit E') AS 'Vit E',
fnGetElementValue(`feedstuffs`.`id`, 'Vit K') AS 'Vit K',
fnGetElementValue(`feedstuffs`.`id`, 'Biotin') AS 'Biotin',
fnGetElementValue(`feedstuffs`.`id`, 'Choline') AS 'Choline',
fnGetElementValue(`feedstuffs`.`id`, 'Folic') AS 'Folic',
fnGetElementValue(`feedstuffs`.`id`, 'Niacin') AS 'Niacin',
fnGetElementValue(`feedstuffs`.`id`, 'Pantot') AS 'Pantot',
fnGetElementValue(`feedstuffs`.`id`, 'Vit B1') AS 'Vit B1',
fnGetElementValue(`feedstuffs`.`id`, 'Vit B2') AS 'Vit B2',
fnGetElementValue(`feedstuffs`.`id`, 'Vit B6') AS 'Vit B6',
fnGetElementValue(`feedstuffs`.`id`, 'Vit B12') AS 'Vit B12',
fnGetElementValue(`feedstuffs`.`id`, 'Vit C') AS 'Vit C',
fnGetElementValue(`feedstuffs`.`id`, 'Inositol') AS 'Inositol',
fnGetElementValue(`feedstuffs`.`id`, 'Cholest') AS 'Cholest'
FROM worldofrations.feedstuffs AS `feedstuffs` ORDER BY `feedstuffs`.`name`